# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gssampler',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/gssampler',
                'lib_path': 'gssampler'},
  'syms': {'gssampler.core': {'gssampler.core.foo': ('core.html#foo', 'gssampler/core.py')}}}
